from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ShikigamiChallengeAssets: 


	# Click Rule Assets
	# 切换至式神1 
	C_SHIKIGAMI_1 = RuleClick(roi_front=(346,177,125,64), roi_back=(346,177,125,64), name="shikigami_1")
	# 切换至式神2 
	C_SHIKIGAMI_2 = RuleClick(roi_front=(340,275,125,64), roi_back=(340,275,125,64), name="shikigami_2")
	# 切换至式神3 
	C_SHIKIGAMI_3 = RuleClick(roi_front=(343,368,125,64), roi_back=(343,368,125,64), name="shikigami_3")
	# description 
	C_SHIKIGAMI_DEBRIS_ENTRY = RuleClick(roi_front=(162,172,129,209), roi_back=(162,172,129,209), name="shikigami_debris_entry")


	# Image Rule Assets
	# 切换到挑战 
	I_SWITCH_CHALLENGE = RuleImage(roi_front=(1062,365,67,54), roi_back=(1062,365,67,54), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_switch_challenge.png")
	# 挑战 
	I_FIRE_CHALLENGE = RuleImage(roi_front=(883,514,121,47), roi_back=(863,481,169,95), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_fire_challenge.png")
	# 式神1 
	I_SHIKIGAMI_1 = RuleImage(roi_front=(483,189.5,25,38), roi_back=(472,173,56,61), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_1.png")
	# 式神2 
	I_SHIKIGAMI_2 = RuleImage(roi_front=(489,284,21,40), roi_back=(472,284,56,61), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_2.png")
	# 式神3 
	I_SHIKIGAMI_3 = RuleImage(roi_front=(489,380,21,37), roi_back=(472,380,56,61), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_3.png")
	# 未发现式神 
	I_NOT_SHIKIGAMI = RuleImage(roi_front=(273,178,41,41), roi_back=(273,178,41,41), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_not_shikigami.png")
	# description 
	I_CHALLENGE_PAGE_CHECK = RuleImage(roi_front=(1079,386,33,32), roi_back=(1079,386,33,32), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_challenge_page_check.png")
	# 入口-契约碎片 
	I_SHIKIGAMI_DEBRIS_ENTRY_X5 = RuleImage(roi_front=(859,229,21,21), roi_back=(563,72,505,427), threshold=0.6, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_entry_x5.png")
	# 入口-契约碎片 
	I_SHIKIGAMI_DEBRIS_ENTRY_X4 = RuleImage(roi_front=(896,210,21,21), roi_back=(563,72,505,427), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_entry_x4.png")
	# 入口-契约碎片 
	I_SHIKIGAMI_DEBRIS_ENTRY_X3 = RuleImage(roi_front=(936,191,21,21), roi_back=(563,72,505,427), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_entry_x3.png")
	# 入口-契约碎片 
	I_SHIKIGAMI_DEBRIS_ENTRY_X2 = RuleImage(roi_front=(975,169,21,21), roi_back=(563,72,505,427), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_entry_x2.png")
	# 入口-契约碎片 
	I_SHIKIGAMI_DEBRIS_ENTRY_X1 = RuleImage(roi_front=(790,217,21,21), roi_back=(563,72,505,427), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_entry_x1.png")
	# 查询未挑战的行 
	I_SHIKIGAMI_DEBRIS_SELECT = RuleImage(roi_front=(421,237,16,17), roi_back=(414,185,33,95), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_select.png")
	# 入口-式神碎片 
	I_SHIKIGAMI_DEBRIS_ENTRY_2 = RuleImage(roi_front=(95,168,37,43), roi_back=(95,168,37,43), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_entry_2.png")
	# 式神碎片 
	I_SHIKIGAMI_DEBRIS_CHECK = RuleImage(roi_front=(592,151,112,30), roi_back=(592,151,112,30), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_check.png")
	# 式神碎片挑战按钮 
	I_SHIKIGAMI_DEBRIS_FIRE = RuleImage(roi_front=(910,534,139,57), roi_back=(910,534,139,57), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_fire.png")
	# description 
	I_SHIKIGAMI_DEBRIS_NO = RuleImage(roi_front=(206,165,33,41), roi_back=(206,165,33,41), threshold=0.8, method="Template matching", file="./tasks/ShikigamiChallenge/res/res_shikigami_debris_no.png")


	# Ocr Rule Assets
	# 式神名称 
	O_SHIKIGAMI_NAME = RuleOcr(roi=(611,184,36,127), area=(611,184,36,127), mode="Single", method="Default", keyword="", name="shikigami_name")
	# 挑战券数量 
	O_CHALLENGE_TICKET = RuleOcr(roi=(545,13,96,33), area=(545,13,96,33), mode="Digit", method="Default", keyword="", name="challenge_ticket")
	# 式神碎片副本式神名称 
	O_SHIKIGAMI_DEBRIS_NAME = RuleOcr(roi=(247,194,105,32), area=(229,180,152,48), mode="Full", method="Default", keyword="", name="shikigami_debris_name")


	# Swipe Rule Assets
	# 下滑 
	S_SHIKIGAMI_DEBRIS_SELECT = RuleSwipe(roi_front=(330,316,84,34), roi_back=(325,196,87,33), mode="default", name="shikigami_debris_select")


