from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class WishAssets: 


	# Image Rule Assets
	# 进入祈愿 
	I_ENTER_WISH = RuleImage(roi_front=(971,636,50,36), roi_back=(971,636,50,36), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_enter_wish.png")
	# 进入祈愿校验 
	I_ENTER_WISH_CHECK = RuleImage(roi_front=(1177,257,37,73), roi_back=(1177,257,37,73), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_enter_wish_check.png")
	# 赠与按钮 
	I_BESTOW = RuleImage(roi_front=(843,284,100,39), roi_back=(807,261,188,90), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_bestow.png")
	# 赠与确认 
	I_BESTOW_CONFIRM = RuleImage(roi_front=(669,401,175,62), roi_back=(669,401,175,62), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_bestow_confirm.png")
	# 切换至好友 
	I_SWITCH_FRIEND_1 = RuleImage(roi_front=(170,608,200,48), roi_back=(170,608,200,48), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_switch_friend_1.png")
	# 切换至好友2 
	I_SWITCH_FRIEND_2 = RuleImage(roi_front=(177,543,192,52), roi_back=(177,543,192,52), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_switch_friend_2.png")
	# 切换至好友校验 
	I_SWITCH_FRIEND_CHECK = RuleImage(roi_front=(173,605,199,50), roi_back=(173,605,199,50), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_switch_friend_check.png")
	# 下滑到底 
	I_SWITCH_END_CHECK = RuleImage(roi_front=(109,559,41,41), roi_back=(109,559,41,41), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_switch_end_check.png")
	# 碎片不足 
	I_SWITCH_END_CHECK_2 = RuleImage(roi_front=(902,185,107,39), roi_back=(888,139,145,101), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_switch_end_check_2.png")
	# 亲密度不足足 
	I_SWITCH_END_CHECK_3 = RuleImage(roi_front=(883,125,147,35), roi_back=(838,75,216,121), threshold=0.8, method="Template matching", file="./tasks/Wish/res/res_switch_end_check_3.png")


	# Ocr Rule Assets
	# Ocr-角色名称 
	O_NAME = RuleOcr(roi=(254,77,233,498), area=(254,77,233,498), mode="Full", method="Default", keyword="", name="name")


	# Swipe Rule Assets
	# 手指向上滑动  
	S_LIST_DOWN = RuleSwipe(roi_front=(450,500,10,10), roi_back=(390,360,10,10), mode="default", name="list_down")


